### PR TITLE
flag for setting the home dir as the path base

### PR DESCRIPTION
**Pull request by theteladras**
This is a proposal for having the option of setting a flag, which would allow us to have the home dir as the base for the provided env paths.

The need for it raises by the fact that a need for a platform independent way of managing the env files.

### CODE REVIEW

**Comment by theteladras** [comment]
@kraenhansen Hey there, I created this PR in order to have a way of setting the home dir as the base for the script. It's open for some time now, I suspect I can close it?

**Comment by kraenhansen** [comment]
@theteladras sorry I hadn't noticed your PR. Can I get you to create an issue describing what you want to achieve and how it would be useful?

**Comment by theteladras** [comment]
@kraenhansen No worries! Sure thing, I'll create it in this few days.

**Comment by theteladras** [comment]
@kraenhansen Issue opened. Can be checked out [here](https://github.com/kraenhansen/dotenv-run-script/issues/3).

**Pull request closed without merging**
