### PR TITLE
adds status code handling

### PR DESCRIPTION
**Pull request by styx0r**
Hi Kræn,

first of all, thank you for the nice package, with the help of dotenv-run-script our package.jsons are cleaner than ever. :)

However, we run into problems when using it for tests. Especially, in github actions we can't see error messages.
The reason is that dotenv-run-script is always returning 0.

Therefore, I added the status code handling in this PR. We are very grateful if the npm package can get an update soon.

Thanks!

### CODE REVIEW

**Comment by nephix** [comment]
I'm also looking forward to this. With `package.json`:

```
  "scripts": {
    "test:unit": "... run some tests ...",
    "development": "dotenv-run-script .env.development --",
  },
```

and then running:

```
$ npm run development test:unit
```

the command does not `exit(1)` even though the `test:unit` target does

**Comment by kraenhansen** [comment]
Thanks a lot for your PR! I honestly don't understand why I hadn't included this in the first version.

Also, sorry for the delay on my part. I had my notifications settings messed up.

**Comment by kraenhansen** [comment]
I'll release this tomorrow when I'm back at my laptop 💻

**Comment by kraenhansen** [comment]
It's out https://github.com/kraenhansen/dotenv-run-script/releases/tag/v0.2.0 - thanks again.

**Comment by styx0r** [comment]
Thank you!

**Pull request merged**
